'PRINTING MATH'
'MATH OPERATORS'
'+ - * / MOD is MODULUS ^ for POWERS'
'MATH FUNCTIONS'
'ABS absolute value. SQR square root'
CLS
PRINT "5 + 10 ="; 5 + 10
PRINT "6 - 5 ="; 6 - 5
PRINT "7 * 6 ="; 7 * 6
PRINT "10 / 2 ="; 10 / 2
PRINT "2 To The Power Of 3 ="; 2 ^ 3
PRINT "Square root of 25 ="; SQR(25)
PRINT "Absolute Value of -5 ="; ABS(-5)
PRINT "5 * 2 + 10 ="; 5 * 2 + 10
PRINT "(5 * 2) + 10 ="; (5 * 2) + 10
PRINT "5 * (2 + 10) ="; 5 * (2 + 10)

